import type { DemoRole } from "@/types/hotel-operations";
import type { Announcement, AnnouncementAudience, AnnouncementDisplayStatus, AnnouncementPriority } from "@/types/announcements";
export const ANNOUNCEMENT_AUDIENCES: AnnouncementAudience[]=["ALL","FRONT_DESK","HOUSEKEEPING","MAINTENANCE"];
export const ANNOUNCEMENT_PRIORITIES: AnnouncementPriority[]=["NORMAL","IMPORTANT","URGENT"];
export const normalizeEmployeeName=(name:string)=>name.trim().toLocaleLowerCase();
export function getAnnouncementDisplayStatus(a:Announcement,now:Date|string=new Date()):AnnouncementDisplayStatus { const time=typeof now==="string"?Date.parse(now):now.getTime(); if(a.archivedAt)return "ARCHIVED"; if(Date.parse(a.startsAt)>time)return "SCHEDULED"; if(a.expiresAt&&Date.parse(a.expiresAt)<=time)return "EXPIRED"; return "ACTIVE"; }
export function isAnnouncementVisibleToRole(a:Announcement,role:DemoRole){return a.audience==="ALL"||a.audience===role||(a.audience==="HOUSEKEEPING"&&role==="HOUSEKEEPING_SUPERVISOR")||(a.audience==="MAINTENANCE"&&role==="MAINTENANCE_MANAGER");}
export const hasEmployeeReadAnnouncement=(a:Announcement,role:DemoRole,name:string)=>Boolean(normalizeEmployeeName(name))&&a.readReceipts.some(r=>r.role===role&&normalizeEmployeeName(r.employeeName)===normalizeEmployeeName(name));
export const getAnnouncementsVisibleToRole=(xs:Announcement[],role:DemoRole)=>xs.filter(a=>isAnnouncementVisibleToRole(a,role));
const byStatus=(s:AnnouncementDisplayStatus)=>(xs:Announcement[],now:Date|string=new Date())=>xs.filter(a=>getAnnouncementDisplayStatus(a,now)===s);
export const getActiveAnnouncements=byStatus("ACTIVE"),getScheduledAnnouncements=byStatus("SCHEDULED"),getExpiredAnnouncements=byStatus("EXPIRED"),getArchivedAnnouncements=byStatus("ARCHIVED");
export function getUnreadAnnouncementsForEmployee(xs:Announcement[],role:DemoRole,name:string|undefined,now:Date|string=new Date()){if(!name?.trim())return null;return xs.filter(a=>isAnnouncementVisibleToRole(a,role)&&getAnnouncementDisplayStatus(a,now)==="ACTIVE"&&!hasEmployeeReadAnnouncement(a,role,name));}
export function getAnnouncementCounts(xs:Announcement[],now:Date|string=new Date()){return {active:getActiveAnnouncements(xs,now).length,scheduled:getScheduledAnnouncements(xs,now).length,expired:getExpiredAnnouncements(xs,now).length,archived:getArchivedAnnouncements(xs,now).length};}
export const getAnnouncementReadReceipts=(a:Announcement)=>[...a.readReceipts].sort((x,y)=>y.readAt.localeCompare(x.readAt)||x.employeeName.localeCompare(y.employeeName)||x.id.localeCompare(y.id));
export const getAnnouncementsCreatedByEmployee=(xs:Announcement[],role:DemoRole,name:string)=>xs.filter(a=>a.createdByRole===role&&normalizeEmployeeName(a.createdByName)===normalizeEmployeeName(name));
export function filterAnnouncements(xs:Announcement[],query:string,audience:AnnouncementAudience|"ALL_AUDIENCES",priority:AnnouncementPriority|"ALL_PRIORITIES"){const q=query.trim().toLowerCase();return xs.filter(a=>(audience==="ALL_AUDIENCES"||a.audience===audience)&&(priority==="ALL_PRIORITIES"||a.priority===priority)&&(!q||[a.title,a.message,a.createdByName,...a.readReceipts.map(r=>r.employeeName)].some(v=>v.toLowerCase().includes(q))));}
const rank={URGENT:0,IMPORTANT:1,NORMAL:2};
export function sortAnnouncementsForEmployee(xs:Announcement[],role:DemoRole,name:string|undefined,status:AnnouncementDisplayStatus){return [...xs].sort((a,b)=>{if(status==="ACTIVE"){if(name){const d=Number(hasEmployeeReadAnnouncement(a,role,name))-Number(hasEmployeeReadAnnouncement(b,role,name));if(d)return d;}return Number(b.isPinned)-Number(a.isPinned)||rank[a.priority]-rank[b.priority]||b.startsAt.localeCompare(a.startsAt)||b.createdAt.localeCompare(a.createdAt)||a.id.localeCompare(b.id);}if(status==="SCHEDULED")return a.startsAt.localeCompare(b.startsAt)||rank[a.priority]-rank[b.priority]||a.id.localeCompare(b.id);const av=status==="ARCHIVED"?a.archivedAt:a.expiresAt,bv=status==="ARCHIVED"?b.archivedAt:b.expiresAt;return (bv??"").localeCompare(av??"")||a.id.localeCompare(b.id);});}
export const defaultAudienceForRole=(role:DemoRole):AnnouncementAudience=>role==="FRONT_DESK"?"FRONT_DESK":role==="HOUSEKEEPING_SUPERVISOR"?"HOUSEKEEPING":"MAINTENANCE";
