import { ANNOUNCEMENT_AUDIENCES, ANNOUNCEMENT_PRIORITIES, normalizeEmployeeName } from "@/lib/announcements";
import type { Announcement, AnnouncementState } from "@/types/announcements";
import type { DemoRole } from "@/types/hotel-operations";
export const ANNOUNCEMENTS_STORAGE_KEY="hotel-ops-web:announcements:v1";
export const EMPTY_ANNOUNCEMENT_STATE:AnnouncementState={version:1,announcements:[],readerProfiles:{}};
const roles:DemoRole[]=["FRONT_DESK","HOUSEKEEPING_SUPERVISOR","MAINTENANCE_MANAGER"];
const str=(x:unknown):x is string=>typeof x==="string"&&x.trim()===x&&x.length>0;
const iso=(x:unknown):x is string=>typeof x==="string"&&!Number.isNaN(Date.parse(x))&&new Date(x).toISOString()===x;
function validAnnouncement(x:unknown):x is Announcement {if(!x||typeof x!=="object")return false;const a=x as Announcement;if(!str(a.id)||!str(a.title)||!str(a.message)||!ANNOUNCEMENT_AUDIENCES.includes(a.audience)||!ANNOUNCEMENT_PRIORITIES.includes(a.priority)||typeof a.isPinned!=="boolean"||!iso(a.startsAt)||a.expiresAt!==null&&(!iso(a.expiresAt)||a.expiresAt<=a.startsAt)||!str(a.createdByName)||!roles.includes(a.createdByRole)||!iso(a.createdAt)||!iso(a.updatedAt)||!Array.isArray(a.readReceipts))return false;if(a.archivedAt===null){if(a.archivedByName!==null||a.archivedByRole!==null)return false;}else if(!iso(a.archivedAt)||!str(a.archivedByName)||!a.archivedByRole||!roles.includes(a.archivedByRole))return false;const ids=new Set<string>(),people=new Set<string>();return a.readReceipts.every(r=>{if(!str(r.id)||!str(r.employeeName)||!roles.includes(r.role)||!iso(r.readAt)||ids.has(r.id))return false;ids.add(r.id);const key=`${r.role}:${normalizeEmployeeName(r.employeeName)}`;if(people.has(key))return false;people.add(key);return true;});}
export function validateAnnouncementState(x:unknown):x is AnnouncementState {if(!x||typeof x!=="object")return false;const s=x as AnnouncementState;if(s.version!==1||!Array.isArray(s.announcements)||!s.readerProfiles||typeof s.readerProfiles!=="object"||Array.isArray(s.readerProfiles))return false;for(const [key,value] of Object.entries(s.readerProfiles))if(!roles.includes(key as DemoRole)||!str(value))return false;const ids=new Set<string>();return s.announcements.every(a=>validAnnouncement(a)&&!ids.has(a.id)&&Boolean(ids.add(a.id)));}
export function parseAnnouncementState(raw:string|null):AnnouncementState {if(!raw)return EMPTY_ANNOUNCEMENT_STATE;try{const x:unknown=JSON.parse(raw);return validateAnnouncementState(x)?x:EMPTY_ANNOUNCEMENT_STATE;}catch{return EMPTY_ANNOUNCEMENT_STATE;}}
export const loadAnnouncementState=()=>typeof window==="undefined"?EMPTY_ANNOUNCEMENT_STATE:parseAnnouncementState(localStorage.getItem(ANNOUNCEMENTS_STORAGE_KEY));
export const saveAnnouncementState=(s:AnnouncementState)=>localStorage.setItem(ANNOUNCEMENTS_STORAGE_KEY,JSON.stringify(s));
