import type { ChecklistItemOutcome, ChecklistSignature, ChecklistTemplateItem, FrontDeskChecklistInstance, FrontDeskChecklistState, FrontDeskChecklistStatus, FrontDeskShift, SignatureStroke } from "@/types/front-desk-checklist";

const labels: Record<FrontDeskShift, string[]> = {
  AM: ["Review the previous shift handoff and unresolved issues.","Review arrivals, departures, VIPs and special requests.","Review open housekeeping and maintenance requests.","Check Front Desk email, internal messages and active announcements.","Verify the lobby and Front Desk area are presentable and supplied.","Verify wake-up calls, transportation and time-sensitive guest requests.","Confirm keys, radios and shared equipment are accounted for.","Confirm the cash bank handoff/count per property procedure.","Document billing, guest recovery or manager follow-up items.","Prepare clear AM-to-PM handoff notes."],
  PM: ["Review the AM shift handoff and unresolved issues.","Review remaining arrivals, VIPs and room-readiness concerns.","Review open housekeeping and maintenance requests.","Check Front Desk email, internal messages and active announcements.","Verify the lobby and Front Desk area are presentable and supplied.","Confirm keys, radios and shared equipment are accounted for.","Confirm the cash bank handoff/count per property procedure.","Document billing, guest recovery or manager follow-up items.","Review time-sensitive requests for the evening and overnight.","Prepare clear PM-to-Night handoff notes."],
  NIGHT: ["Review the PM shift handoff and unresolved issues.","Review remaining arrivals, no-shows and special requests.","Review open housekeeping and maintenance requests.","Verify wake-up calls, transportation and early-morning requests.","Confirm keys, radios and shared equipment are accounted for.","Confirm the cash bank handoff/count per property procedure.","Confirm required overnight security checks per property procedure.","Prepare and verify Night Audit readiness.","Document incidents, billing issues and manager follow-up items.","Prepare clear Night-to-AM handoff notes and morning reports."]
};
export const FRONT_DESK_SHIFTS: FrontDeskShift[] = ["AM", "PM", "NIGHT"];
export const FRONT_DESK_TEMPLATES: Record<FrontDeskShift, ChecklistTemplateItem[]> = Object.fromEntries(FRONT_DESK_SHIFTS.map(shift => [shift, labels[shift].map((label,index)=>({id:`v1-${shift.toLowerCase()}-${index+1}`,label,order:index+1}))])) as Record<FrontDeskShift, ChecklistTemplateItem[]>;
export function formatLocalDate(date = new Date()): string { const y=date.getFullYear(); const m=String(date.getMonth()+1).padStart(2,"0"); const d=String(date.getDate()).padStart(2,"0"); return `${y}-${m}-${d}`; }
export function clampDate(date:string, today=formatLocalDate()):string { return /^\d{4}-\d{2}-\d{2}$/.test(date) && date <= today ? date : today; }
export function shiftDate(date:string, days:number):string { const [y,m,d]=date.split("-").map(Number); const value=new Date(y,m-1,d); value.setDate(value.getDate()+days); return formatLocalDate(value); }
export function createBlankChecklist(localDate:string, shift:FrontDeskShift, now=new Date().toISOString()):FrontDeskChecklistInstance { return {id:`${localDate}:${shift}`,localDate,shift,templateVersion:1,items:FRONT_DESK_TEMPLATES[shift].map(x=>({templateItemId:x.id,labelSnapshot:x.label,order:x.order,outcome:"PENDING",note:null,resolvedAt:null})),generalNotes:null,signature:null,createdAt:now,updatedAt:now}; }
export function getFrontDeskChecklistStatus(i:FrontDeskChecklistInstance):FrontDeskChecklistStatus { if(i.signature) return "SIGNED"; const resolved=i.items.some(x=>x.outcome!=="PENDING"); const notes=Boolean(i.generalNotes?.trim()); if(!resolved&&!notes)return "NOT_STARTED"; return i.items.every(x=>x.outcome!=="PENDING"&&(x.outcome!=="EXCEPTION"||Boolean(x.note?.trim())))?"READY_TO_SIGN":"IN_PROGRESS"; }
export function isMeaningfulSignature(strokes:SignatureStroke[]):boolean { return strokes.some(s=>s.points.length>=3) && strokes.reduce((n,s)=>n+s.points.length,0)>=3; }
function replace(state:FrontDeskChecklistState, instance:FrontDeskChecklistInstance):FrontDeskChecklistState { if(instance.signature) throw new Error("Signed checklists are locked."); const index=state.instances.findIndex(x=>x.localDate===instance.localDate&&x.shift===instance.shift); return {version:1,instances:index<0?[...state.instances,instance]:state.instances.map((x,i)=>i===index?instance:x)}; }
export function updateChecklistItem(state:FrontDeskChecklistState, base:FrontDeskChecklistInstance, itemId:string, outcome:ChecklistItemOutcome, note?:string, now=new Date().toISOString()):FrontDeskChecklistState { if(base.signature) throw new Error("Signed checklists are locked."); if(outcome==="EXCEPTION"&&!note?.trim()) throw new Error("An exception explanation is required."); const instance={...base,updatedAt:now,items:base.items.map(x=>x.templateItemId===itemId?{...x,outcome,note:outcome==="EXCEPTION"?note!.trim():null,resolvedAt:outcome==="PENDING"?null:now}:x)}; return replace(state,instance); }
export function updateGeneralNotes(state:FrontDeskChecklistState, base:FrontDeskChecklistInstance, notes:string, now=new Date().toISOString()):FrontDeskChecklistState { return replace(state,{...base,generalNotes:notes.trim()||null,updatedAt:now}); }
export function signChecklist(state:FrontDeskChecklistState, base:FrontDeskChecklistInstance, signedBy:string, strokes:SignatureStroke[], now=new Date().toISOString()):FrontDeskChecklistState { if(base.signature) throw new Error("Signed checklists are locked."); if(getFrontDeskChecklistStatus(base)!=="READY_TO_SIGN")throw new Error("Resolve every checklist item before signing."); if(!signedBy.trim())throw new Error("Printed Agent Name is required."); if(!isMeaningfulSignature(strokes))throw new Error("Draw a meaningful signature."); const signature:ChecklistSignature={signedBy:signedBy.trim(),signedAt:now,strokes}; const signed={...base,signature,updatedAt:now}; const index=state.instances.findIndex(x=>x.localDate===base.localDate&&x.shift===base.shift); return {version:1,instances:index<0?[...state.instances,signed]:state.instances.map((x,i)=>i===index?signed:x)}; }
export function getDailyStatuses(state:FrontDeskChecklistState,date:string):Record<FrontDeskShift,FrontDeskChecklistStatus>{ return Object.fromEntries(FRONT_DESK_SHIFTS.map(shift=>[shift,getFrontDeskChecklistStatus(state.instances.find(x=>x.localDate===date&&x.shift===shift)??createBlankChecklist(date,shift))])) as Record<FrontDeskShift,FrontDeskChecklistStatus>; }
export function getDailySummary(state:FrontDeskChecklistState,date:string):Record<FrontDeskChecklistStatus,number>{ const result={NOT_STARTED:0,IN_PROGRESS:0,READY_TO_SIGN:0,SIGNED:0}; Object.values(getDailyStatuses(state,date)).forEach(x=>result[x]++); return result; }
export function getHistoricalSigned(state:FrontDeskChecklistState){return state.instances.filter(x=>x.signature).sort((a,b)=>b.localDate.localeCompare(a.localDate)||b.shift.localeCompare(a.shift));}
