import {buildRooms} from "@/lib/rooms";
import type {IncidentCategory,IncidentDisplayStatus,IncidentReport,IncidentSeverity} from "@/types/incidents";
import type {SignatureStroke} from "@/types/signature";
export const INCIDENT_CATEGORIES:IncidentCategory[]=["GUEST_COMPLAINT","INJURY_OR_MEDICAL","SECURITY","PROPERTY_DAMAGE","EMPLOYEE_INCIDENT","FIRE_OR_EVACUATION","POLICE_OR_EMERGENCY_RESPONSE","THEFT_OR_MISSING_PROPERTY","BILLING_OR_GUEST_RECOVERY","MAINTENANCE_OR_SAFETY","OPERATIONAL_DISRUPTION","OTHER"];
export const INCIDENT_SEVERITIES:IncidentSeverity[]=["LOW","MEDIUM","HIGH","CRITICAL"];
export const validIso=(v:unknown):v is string=>typeof v==="string"&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
export const validRoom=(v:number|null)=>v===null||buildRooms().some(r=>r.number===v);
export const meaningfulSignature=(s:SignatureStroke[])=>s.length>0&&s.reduce((n,x)=>n+x.points.length,0)>=3;
export function getIncidentDisplayStatus(i:IncidentReport):IncidentDisplayStatus{if(i.submittedAt&&i.reporterAttestation){if(i.closure)return "CLOSED";return i.followUpRequired?"FOLLOW_UP_REQUIRED":"SUBMITTED"}return "DRAFT"}
export function generateNextIncidentNumber(records:readonly IncidentReport[],reportedAt:string){const d=new Date(reportedAt);if(Number.isNaN(d.valueOf()))throw new Error("Invalid reported date");const part=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}`;const re=new RegExp(`^INC-${part}-(\\d+)$`);const used=new Set(records.map(x=>x.incidentNumber));let seq=Math.max(0,...records.map(x=>Number(x.incidentNumber.match(re)?.[1]??0)))+1;let value;do value=`INC-${part}-${String(seq++).padStart(3,"0")}`;while(used.has(value));return value}
export function validateIncidentForSubmission(i:IncidentReport,printedName="",strokes:SignatureStroke[]=[]){const errors:string[]=[];if(!INCIDENT_CATEGORIES.includes(i.category))errors.push("Select a category.");if(!INCIDENT_SEVERITIES.includes(i.severity))errors.push("Select a severity.");for(const [v,n] of [[i.title,"title"],[i.location,"location"],[i.description,"description"],[i.immediateActionsTaken,"immediate actions"]] as const)if(!v.trim())errors.push(`Enter ${n}.`);if(!validIso(i.occurredAt)||!validIso(i.reportedAt))errors.push("Enter valid incident times.");else {if(i.occurredAt>i.reportedAt)errors.push("Occurred time cannot be after reported time.");if(Date.parse(i.reportedAt)>Date.now()+5*60_000)errors.push("Reported time is in the future.")}if(!validRoom(i.roomNumber))errors.push("Select a valid room.");if(i.emergencyServices.policeNotified||i.emergencyServices.fireDepartmentNotified||i.emergencyServices.emsNotified){if(!validIso(i.emergencyServices.contactedAt))errors.push("Enter the authority contact time.")}if(i.guestRecovery.provided){if(i.guestRecovery.recoveryType==="NONE"||!i.guestRecovery.details?.trim())errors.push("Enter guest recovery type and details.")}if(i.guestRecovery.amount!==null&&(!Number.isFinite(i.guestRecovery.amount)||i.guestRecovery.amount<0||Math.round(i.guestRecovery.amount*100)!==i.guestRecovery.amount*100))errors.push("Enter a valid recovery amount.");if(i.followUpRequired&&(!i.followUpOwner?.trim()||!validIso(i.followUpDueAt)))errors.push("Enter follow-up owner and due time.");if(!printedName.trim())errors.push("Enter reporter name.");if(!meaningfulSignature(strokes))errors.push("Provide a meaningful signature.");return errors}
export const getIncidentById=(a:readonly IncidentReport[],id:string)=>a.find(x=>x.id===id)??null;
export const isIncidentDraftEditable=(i:IncidentReport)=>getIncidentDisplayStatus(i)==="DRAFT";
export const canAddIncidentFollowUp=(i:IncidentReport)=>getIncidentDisplayStatus(i)!=="DRAFT"&&!i.closure;
export const canCloseIncident=canAddIncidentFollowUp;
export const canGenerateIncidentPdf=(i:IncidentReport)=>getIncidentDisplayStatus(i)!=="DRAFT";
export const getOpenIncidents=(a:readonly IncidentReport[])=>a.filter(i=>["SUBMITTED","FOLLOW_UP_REQUIRED"].includes(getIncidentDisplayStatus(i)));
export const getFollowUpRequiredIncidents=(a:readonly IncidentReport[])=>a.filter(i=>getIncidentDisplayStatus(i)==="FOLLOW_UP_REQUIRED");
export const getOverdueIncidents=(a:readonly IncidentReport[],now=new Date().toISOString())=>getFollowUpRequiredIncidents(a).filter(i=>Boolean(i.followUpDueAt&&i.followUpDueAt<now));
export const getCriticalOpenIncidents=(a:readonly IncidentReport[])=>getOpenIncidents(a).filter(i=>i.severity==="CRITICAL");
export function getIncidentCounts(a:readonly IncidentReport[]){return{drafts:a.filter(i=>getIncidentDisplayStatus(i)==="DRAFT").length,open:getOpenIncidents(a).length,followUpRequired:getFollowUpRequiredIncidents(a).length,criticalOpen:getCriticalOpenIncidents(a).length,closed:a.filter(i=>getIncidentDisplayStatus(i)==="CLOSED").length,overdue:getOverdueIncidents(a).length}}
export const getIncidentHistory=(i:IncidentReport)=>[...i.followUps].sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
export type IncidentFilters={query?:string;status?:IncidentDisplayStatus|"ALL";category?:IncidentCategory|"ALL";severity?:IncidentSeverity|"ALL";from?:string;to?:string};
export function filterIncidents(a:readonly IncidentReport[],f:IncidentFilters){const q=f.query?.trim().toLowerCase();return a.filter(i=>(!f.status||f.status==="ALL"||getIncidentDisplayStatus(i)===f.status)&&(!f.category||f.category==="ALL"||i.category===f.category)&&(!f.severity||f.severity==="ALL"||i.severity===f.severity)&&(!f.from||i.occurredAt>=f.from)&&(!f.to||i.occurredAt<=`${f.to}T23:59:59.999Z`)&&(!q||[i.incidentNumber,i.title,i.description,i.location,String(i.roomNumber??""),...i.involvedPeople.map(x=>x.name),...i.witnesses.map(x=>x.name),i.reporterAttestation?.printedName,...i.followUps.map(x=>x.note),i.closure?.resolutionNote].some(x=>x?.toLowerCase().includes(q))))}
export function sortIncidents(a:readonly IncidentReport[],kind:"OPEN"|"DRAFT"|"CLOSED"|"ALL"="ALL",now=new Date().toISOString()){const rank={CRITICAL:0,HIGH:1,MEDIUM:2,LOW:3};return [...a].sort((x,y)=>kind==="DRAFT"?y.updatedAt.localeCompare(x.updatedAt)||x.incidentNumber.localeCompare(y.incidentNumber):kind==="CLOSED"?(y.closure?.closedAt??"").localeCompare(x.closure?.closedAt??"")||x.incidentNumber.localeCompare(y.incidentNumber):rank[x.severity]-rank[y.severity]||Number(Boolean(y.followUpDueAt&&y.followUpDueAt<now))-Number(Boolean(x.followUpDueAt&&x.followUpDueAt<now))||y.occurredAt.localeCompare(x.occurredAt)||x.incidentNumber.localeCompare(y.incidentNumber))}
