import {INCIDENT_CATEGORIES,INCIDENT_SEVERITIES,getIncidentDisplayStatus,validIso,validRoom} from "@/lib/incidents";
import type {IncidentReport,IncidentReportState} from "@/types/incidents";
export const INCIDENT_REPORTS_STORAGE_KEY="hotel-ops-web:incident-reports:v1";
export const EMPTY_INCIDENT_REPORT_STATE:IncidentReportState={version:1,incidents:[]};
const roles=["FRONT_DESK","HOUSEKEEPING_SUPERVISOR","MAINTENANCE_MANAGER"];
const clean=(x:unknown):x is string=>typeof x==="string"&&x.length>0&&x.trim()===x;
const draftText=(x:unknown):x is string=>typeof x==="string"&&x.trim()===x;
const nullable=(x:unknown)=>x===null||clean(x);
const unique=(a:{id:string}[])=>new Set(a.map(x=>x.id)).size===a.length;
function validIncident(x:unknown):x is IncidentReport{if(!x||typeof x!=="object")return false;const i=x as IncidentReport;if(!clean(i.id)||!/^INC-\d{8}-\d{3,}$/.test(i.incidentNumber)||!INCIDENT_CATEGORIES.includes(i.category)||!INCIDENT_SEVERITIES.includes(i.severity)||!draftText(i.title)||!validIso(i.occurredAt)||!validIso(i.reportedAt)||i.occurredAt>i.reportedAt||!draftText(i.location)||!validRoom(i.roomNumber)||!draftText(i.description)||!draftText(i.immediateActionsTaken)||!validIso(i.createdAt)||!validIso(i.updatedAt)||!Array.isArray(i.involvedPeople)||!Array.isArray(i.witnesses)||!Array.isArray(i.followUps)||!unique(i.involvedPeople)||!unique(i.witnesses)||!unique(i.followUps))return false;
if(!i.involvedPeople.every(p=>clean(p.id)&&["GUEST","EMPLOYEE","VISITOR","CONTRACTOR","OTHER"].includes(p.personType)&&clean(p.name)&&nullable(p.contactInformation)&&validRoom(p.roomNumber)&&nullable(p.notes)))return false;
if(!i.witnesses.every(w=>clean(w.id)&&clean(w.name)&&nullable(w.contactInformation)&&nullable(w.statement)))return false;
const e=i.emergencyServices;if(!e||[e.hotelSecurityNotified,e.policeNotified,e.fireDepartmentNotified,e.emsNotified].some(v=>typeof v!=="boolean")||!nullable(e.agencyReferenceNumber)||!nullable(e.details)||((e.policeNotified||e.fireDepartmentNotified||e.emsNotified)&&!validIso(e.contactedAt))||(!e.policeNotified&&!e.fireDepartmentNotified&&!e.emsNotified&&e.contactedAt!==null&&!validIso(e.contactedAt)))return false;
const g=i.guestRecovery;if(!g||typeof g.provided!=="boolean"||g.currency!=="USD"||!["NONE","REFUND","DISCOUNT","POINTS","COMPLIMENTARY_ITEM","ROOM_MOVE","LATE_CHECKOUT","OTHER"].includes(g.recoveryType)||!nullable(g.details)||!nullable(g.approvedBy)||g.amount!==null&&(!Number.isFinite(g.amount)||g.amount<0||Math.round(g.amount*100)!==g.amount*100)||(!g.provided&&(g.recoveryType!=="NONE"||g.amount!==null))||(g.provided&&(g.recoveryType==="NONE"||!g.details)))return false;
if(typeof i.followUpRequired!=="boolean"||i.followUpRequired&&(!clean(i.followUpOwner)||!validIso(i.followUpDueAt))||!i.followUpRequired&&(i.followUpOwner!==null||i.followUpDueAt!==null))return false;
const submitted=i.submittedAt!==null||i.reporterAttestation!==null;if((i.submittedAt===null)!==(i.reporterAttestation===null))return false;if(submitted){const a=i.reporterAttestation!;if(!validIso(i.submittedAt)||!clean(a.printedName)||!roles.includes(a.role)||!validIso(a.signedAt)||!Array.isArray(a.signatureStrokes)||!a.signatureStrokes.length||!a.signatureStrokes.every(s=>Array.isArray(s.points)&&s.points.length>=2&&s.points.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=0&&p.x<=1&&p.y>=0&&p.y<=1)))return false;}else if(i.followUps.length||i.closure)return false;
if(submitted&&(!clean(i.title)||!clean(i.location)||!clean(i.description)||!clean(i.immediateActionsTaken)))return false;if(!i.followUps.every(f=>clean(f.id)&&clean(f.note)&&clean(f.addedByName)&&roles.includes(f.addedByRole)&&validIso(f.createdAt)))return false;if(i.closure&&(!submitted||!clean(i.closure.resolutionNote)||!clean(i.closure.closedByName)||!roles.includes(i.closure.closedByRole)||!validIso(i.closure.closedAt)))return false;return ["DRAFT","SUBMITTED","FOLLOW_UP_REQUIRED","CLOSED"].includes(getIncidentDisplayStatus(i));}
export function validateIncidentReportState(x:unknown):x is IncidentReportState{if(!x||typeof x!=="object")return false;const s=x as IncidentReportState;if(s.version!==1||!Array.isArray(s.incidents)||!s.incidents.every(validIncident))return false;return new Set(s.incidents.map(i=>i.id)).size===s.incidents.length&&new Set(s.incidents.map(i=>i.incidentNumber)).size===s.incidents.length}
export function parseIncidentReportState(raw:string|null){if(!raw)return EMPTY_INCIDENT_REPORT_STATE;try{const value:unknown=JSON.parse(raw);return validateIncidentReportState(value)?value:EMPTY_INCIDENT_REPORT_STATE}catch{return EMPTY_INCIDENT_REPORT_STATE}}
export const loadIncidentReportState=()=>typeof window==="undefined"?EMPTY_INCIDENT_REPORT_STATE:parseIncidentReportState(localStorage.getItem(INCIDENT_REPORTS_STORAGE_KEY));
export const saveIncidentReportState=(s:IncidentReportState)=>localStorage.setItem(INCIDENT_REPORTS_STORAGE_KEY,JSON.stringify(s));
