import type { LostFoundItem, LostFoundState } from "@/types/lost-found";
export const LOST_FOUND_STORAGE_KEY = "hotel-ops-web:lost-found:v1";
export const SEEDED_LOST_FOUND_STATE: LostFoundState = { version: 1, items: [
  seed("lf-seed-phone", "Black smartphone", "ELECTRONICS", "2026-08-04T14:20:00.000Z", "Lobby sofa", null, "Security locker A3", "OPEN"),
  { ...seed("lf-seed-jacket", "Blue denim jacket", "CLOTHING", "2026-08-03T18:10:00.000Z", "Restaurant", 204, "Housekeeping cage 2", "CLAIMED"), guestName: "Jordan Lee", claimedAt: "2026-08-05T09:00:00.000Z", updatedAt: "2026-08-05T09:00:00.000Z" },
  { ...seed("lf-seed-wallet", "Brown leather wallet", "WALLET_OR_MONEY", "2026-08-01T07:30:00.000Z", "Room 317", 317, "Front desk safe", "RETURNED"), guestName: "Casey Morgan", returnedAt: "2026-08-02T16:00:00.000Z", updatedAt: "2026-08-02T16:00:00.000Z" },
] };
function seed(id: string, itemName: string, category: LostFoundItem["category"], foundAt: string, foundLocation: string, roomNumber: number | null, storageLocation: string, status: LostFoundItem["status"]): LostFoundItem { return { id, itemName, category, description: "", foundAt, foundLocation, roomNumber, storageLocation, guestName: null, guestContact: null, notes: null, status, createdAt: foundAt, updatedAt: foundAt, claimedAt: null, returnedAt: null, disposedAt: null }; }
export function parseLostFoundState(raw: string | null): LostFoundState | null { try { const value: unknown = raw ? JSON.parse(raw) : null; return isState(value) ? value : null; } catch { return null; } }
export function loadLostFoundState(): LostFoundState { if (typeof window === "undefined") return SEEDED_LOST_FOUND_STATE; try { return parseLostFoundState(localStorage.getItem(LOST_FOUND_STORAGE_KEY)) ?? SEEDED_LOST_FOUND_STATE; } catch { return SEEDED_LOST_FOUND_STATE; } }
export function saveLostFoundState(state: LostFoundState) { if (typeof window !== "undefined") localStorage.setItem(LOST_FOUND_STORAGE_KEY, JSON.stringify(state)); }
function isState(value: unknown): value is LostFoundState { if (!value || typeof value !== "object") return false; const state = value as Partial<LostFoundState>; return state.version === 1 && Array.isArray(state.items) && state.items.every(isItem); }
function isItem(value: unknown): value is LostFoundItem { if (!value || typeof value !== "object") return false; const i = value as Partial<LostFoundItem>; const nullableString = (v: unknown) => v === null || typeof v === "string"; return typeof i.id === "string" && typeof i.itemName === "string" && ["ELECTRONICS","CLOTHING","JEWELRY","IDENTIFICATION","WALLET_OR_MONEY","KEYS","BAG","OTHER"].includes(i.category ?? "") && typeof i.description === "string" && typeof i.foundAt === "string" && typeof i.foundLocation === "string" && (i.roomNumber === null || typeof i.roomNumber === "number") && typeof i.storageLocation === "string" && nullableString(i.guestName) && nullableString(i.guestContact) && nullableString(i.notes) && ["OPEN", "CLAIMED", "RETURNED", "DISPOSED"].includes(i.status ?? "") && typeof i.createdAt === "string" && typeof i.updatedAt === "string" && nullableString(i.claimedAt) && nullableString(i.returnedAt) && nullableString(i.disposedAt); }
