import type { ActorLabel, LogBookEntry, LogBookEventType, PrototypeState, Todo, TodoPriority, TodoStatus, TodoType } from "@/types/hotel-operations";
export const PROTOTYPE_STORAGE_KEY_V1 = "hotel-ops-web:prototype:v1";
export const PROTOTYPE_STORAGE_KEY_V2 = "hotel-ops-web:prototype:v2";
export const PROTOTYPE_STORAGE_KEY_V3 = "hotel-ops-web:prototype:v3";
export const PROTOTYPE_STORAGE_KEY = "hotel-ops-web:prototype:v4";
type LegacyTodo = Partial<Omit<Todo, "status" | "priority">> & { id: string; roomNumber: number; type: TodoType; details: string; status?: string; priority?: string };
type LegacyLogEntry = Partial<LogBookEntry> & { id: string; createdAt: string; message: string; category: string; roomNumber?: number | null; todoId?: string | null };
type LegacyState = { version: 1 | 2 | 3 | 4; todos: unknown[]; logEntries: unknown[] };
const base = { startedAt: null, startedBy: null, completedAt: null, completedBy: null, resolutionNote: null, unableAt: null, unableBy: null, unableReason: null, unableNote: null, cancelledAt: null, cancelledBy: null, cancellationReason: null, deletedAt: null, deletedBy: null };
export const SEEDED_PROTOTYPE_STATE: PrototypeState = { version: 4, todos: [
 todo("seed-todo-204", 204, "HOUSEKEEPING_REQUEST", "URGENT", "Towel Set", 2, "Guest requested delivery to the room.", "OPEN", "2026-08-05T10:24:00.000Z"),
 todo("seed-todo-317", 317, "MAINTENANCE_ISSUE", "NORMAL", "Slow-Draining Sink", null, "Reported during room turnover.", "OPEN", "2026-08-05T09:48:00.000Z"),
 { ...todo("seed-todo-508", 508, "HOUSEKEEPING_REQUEST", "NORMAL", "Missing Robe", 1, "Flagged for supervisor review.", "IN_PROGRESS", "2026-08-05T07:40:00.000Z"), startedAt: "2026-08-05T07:55:00.000Z", startedBy: "Housekeeping Supervisor", updatedAt: "2026-08-05T07:55:00.000Z", updatedBy: "Housekeeping Supervisor" },
 { ...todo("seed-todo-419-unable", 419, "MAINTENANCE_ISSUE", "URGENT", "Air Conditioner Not Cooling", null, "Guest reports room is warm.", "UNABLE_TO_COMPLETE", "2026-08-05T08:05:00.000Z"), startedAt: "2026-08-05T08:12:00.000Z", startedBy: "Maintenance Manager", unableAt: "2026-08-05T08:28:00.000Z", unableBy: "Maintenance Manager", unableReason: "Parts Required", unableNote: "Replacement capacitor is not available on property.", updatedAt: "2026-08-05T08:28:00.000Z", updatedBy: "Maintenance Manager" },
 { ...todo("seed-todo-112-completed", 112, "HOUSEKEEPING_REQUEST", "NORMAL", "Extra Pillows", 2, null, "COMPLETED", "2026-08-05T06:20:00.000Z"), startedAt: "2026-08-05T06:30:00.000Z", startedBy: "Housekeeping Supervisor", completedAt: "2026-08-05T06:42:00.000Z", completedBy: "Housekeeping Supervisor", resolutionNote: "Delivered two pillows and confirmed with the guest.", updatedAt: "2026-08-05T06:42:00.000Z", updatedBy: "Housekeeping Supervisor" },
 { ...todo("seed-todo-226-cancelled", 226, "MAINTENANCE_ISSUE", "NORMAL", "Television Not Working", null, "Guest called back before dispatch.", "CANCELLED", "2026-08-05T06:50:00.000Z"), cancelledAt: "2026-08-05T07:02:00.000Z", cancelledBy: "Front Desk", cancellationReason: "Guest No Longer Needs Item", updatedAt: "2026-08-05T07:02:00.000Z", updatedBy: "Front Desk" },
 { ...todo("seed-todo-hidden", 120, "HOUSEKEEPING_REQUEST", "NORMAL", "Toiletries", 1, null, "DELETED", "2026-08-04T17:20:00.000Z"), deletedAt: "2026-08-04T17:42:00.000Z", deletedBy: "Front Desk", updatedAt: "2026-08-04T17:42:00.000Z", updatedBy: "Front Desk" }], logEntries: [
 log("seed-log-204", "2026-08-05T10:24:00.000Z", 204, "Housekeeping", "seed-todo-204", "CREATED", "Front Desk", "Created by Front Desk for Room 204: Towel Set."),
 log("seed-log-317", "2026-08-05T09:48:00.000Z", 317, "Maintenance", "seed-todo-317", "CREATED", "Front Desk", "Maintenance issue reported for Room 317: Slow-Draining Sink."),
 log("seed-log-operations-1", "2026-08-05T08:15:00.000Z", null, "Operations", null, "NOTE", null, "Night audit completed with no escalations."),
 log("seed-log-508-created", "2026-08-05T07:40:00.000Z", 508, "Housekeeping", "seed-todo-508", "CREATED", "Front Desk", "Created by Front Desk for Room 508: Missing Robe."),
 log("seed-log-508-started", "2026-08-05T07:55:00.000Z", 508, "Housekeeping", "seed-todo-508", "STARTED", "Housekeeping Supervisor", "Work started for Room 508: Missing Robe."),
 log("seed-log-419-created", "2026-08-05T08:05:00.000Z", 419, "Maintenance", "seed-todo-419-unable", "CREATED", "Front Desk", "Created by Front Desk for Room 419: Air Conditioner Not Cooling."),
 log("seed-log-419-started", "2026-08-05T08:12:00.000Z", 419, "Maintenance", "seed-todo-419-unable", "STARTED", "Maintenance Manager", "Work started for Room 419: Air Conditioner Not Cooling."),
 log("seed-log-419-unable", "2026-08-05T08:28:00.000Z", 419, "Maintenance", "seed-todo-419-unable", "UNABLE_TO_COMPLETE", "Maintenance Manager", "Unable to complete request for Room 419: Air Conditioner Not Cooling.", "Parts Required", "Replacement capacitor is not available on property."),
 log("seed-log-112-completed", "2026-08-05T06:42:00.000Z", 112, "Housekeeping", "seed-todo-112-completed", "COMPLETED", "Housekeeping Supervisor", "Housekeeping request completed for Room 112: Extra Pillows.", null, "Delivered two pillows and confirmed with the guest."),
 log("seed-log-226-cancelled", "2026-08-05T07:02:00.000Z", 226, "Maintenance", "seed-todo-226-cancelled", "CANCELLED", "Front Desk", "Request cancelled for Room 226: Television Not Working.", "Guest No Longer Needs Item") ] };
function todo(id: string, roomNumber: number, type: TodoType, priority: TodoPriority, details: string, quantity: number | null, note: string | null, status: TodoStatus, createdAt: string): Todo { return { id, roomNumber, type, priority, details, quantity, note, status, createdAt, updatedAt: createdAt, updatedBy: "Front Desk", ...base }; }
function log(id: string, createdAt: string, roomNumber: number | null, category: LogBookEntry["category"], todoId: string | null, eventType: LogBookEventType, actor: ActorLabel | null, message: string, reason: string | null = null, note: string | null = null): LogBookEntry { return { id, createdAt, roomNumber, message, category, todoId, eventType, actor, reason, note }; }
export function loadPrototypeState(): PrototypeState { if (typeof window === "undefined") return SEEDED_PROTOTYPE_STATE; for (const key of [PROTOTYPE_STORAGE_KEY, PROTOTYPE_STORAGE_KEY_V3, PROTOTYPE_STORAGE_KEY_V2, PROTOTYPE_STORAGE_KEY_V1]) { const value = readStoredValue(key); if (isLegacyState(value)) return key === PROTOTYPE_STORAGE_KEY ? migrateState(value) : saveAndReturn(migrateState(value)); } return SEEDED_PROTOTYPE_STATE; }
export function savePrototypeState(state: PrototypeState): void { if (typeof window === "undefined") return; window.localStorage.setItem(PROTOTYPE_STORAGE_KEY, JSON.stringify(state)); }
function saveAndReturn(state: PrototypeState): PrototypeState { savePrototypeState(state); return state; }
function readStoredValue(key: string): unknown { try { const storedValue = window.localStorage.getItem(key); return storedValue ? JSON.parse(storedValue) : null; } catch { return null; } }
function migrateState(state: LegacyState): PrototypeState { return { version: 4, todos: state.todos.filter(isLegacyTodo).map(migrateTodo), logEntries: state.logEntries.filter(isLegacyLogEntry).map(migrateLogEntry) }; }
function migrateTodo(t: LegacyTodo): Todo { const status = normalizeStatus(t.status); const completedAt = typeof t.completedAt === "string" ? t.completedAt : null; const deletedAt = typeof t.deletedAt === "string" ? t.deletedAt : null; return { id: t.id, roomNumber: t.roomNumber, type: t.type, priority: t.priority === "URGENT" ? "URGENT" : "NORMAL", details: t.details, quantity: t.type === "HOUSEKEEPING_REQUEST" ? t.quantity ?? 1 : null, note: typeof t.note === "string" ? t.note : null, status, createdAt: typeof t.createdAt === "string" ? t.createdAt : new Date(0).toISOString(), updatedAt: typeof t.updatedAt === "string" ? t.updatedAt : completedAt ?? deletedAt ?? (typeof t.createdAt === "string" ? t.createdAt : new Date(0).toISOString()), updatedBy: normalizeActor(t.updatedBy ?? t.completedBy ?? t.deletedBy), startedAt: typeof t.startedAt === "string" ? t.startedAt : null, startedBy: normalizeActor(t.startedBy), completedAt, completedBy: normalizeActor(t.completedBy), resolutionNote: typeof t.resolutionNote === "string" ? t.resolutionNote : null, unableAt: typeof t.unableAt === "string" ? t.unableAt : null, unableBy: normalizeActor(t.unableBy), unableReason: typeof t.unableReason === "string" ? t.unableReason : null, unableNote: typeof t.unableNote === "string" ? t.unableNote : null, cancelledAt: typeof t.cancelledAt === "string" ? t.cancelledAt : null, cancelledBy: normalizeActor(t.cancelledBy), cancellationReason: typeof t.cancellationReason === "string" ? t.cancellationReason : null, deletedAt, deletedBy: normalizeActor(t.deletedBy) }; }
function migrateLogEntry(entry: LegacyLogEntry): LogBookEntry { return { id: entry.id, createdAt: entry.createdAt, roomNumber: typeof entry.roomNumber === "number" ? entry.roomNumber : null, message: entry.message, category: entry.category === "Housekeeping" || entry.category === "Maintenance" ? entry.category : "Operations", todoId: typeof entry.todoId === "string" ? entry.todoId : null, eventType: normalizeEventType(entry.eventType, entry.message), actor: normalizeActor(entry.actor), reason: typeof entry.reason === "string" ? entry.reason : null, note: typeof entry.note === "string" ? entry.note : null }; }
function normalizeStatus(status: string | undefined): TodoStatus { return status === "COMPLETED" || status === "DELETED" || status === "IN_PROGRESS" || status === "UNABLE_TO_COMPLETE" || status === "CANCELLED" ? status : "OPEN"; }
function normalizeEventType(eventType: unknown, message: string): LogBookEventType { if (eventType === "CREATED" || eventType === "UPDATED" || eventType === "STARTED" || eventType === "COMPLETED" || eventType === "UNABLE_TO_COMPLETE" || eventType === "REOPENED" || eventType === "CANCELLED" || eventType === "DELETED" || eventType === "NOTE") return eventType; const lower = message.toLowerCase(); if (lower.includes("completed")) return "COMPLETED"; if (lower.includes("deleted")) return "DELETED"; if (lower.includes("updated") || lower.includes("changed") || lower.includes("moved")) return "UPDATED"; if (lower.includes("request") || lower.includes("reported") || lower.includes("created")) return "CREATED"; return "NOTE"; }
function normalizeActor(actor: unknown): ActorLabel | null { return actor === "Front Desk" || actor === "Housekeeping Supervisor" || actor === "Maintenance Manager" ? actor : null; }
function isLegacyState(value: unknown): value is LegacyState { if (!value || typeof value !== "object") return false; const c = value as Partial<LegacyState>; return (c.version === 1 || c.version === 2 || c.version === 3 || c.version === 4) && Array.isArray(c.todos) && Array.isArray(c.logEntries); }
function isLegacyTodo(todo: unknown): todo is LegacyTodo { if (!todo || typeof todo !== "object") return false; const c = todo as Partial<LegacyTodo>; return typeof c.id === "string" && typeof c.roomNumber === "number" && (c.type === "HOUSEKEEPING_REQUEST" || c.type === "MAINTENANCE_ISSUE") && typeof c.details === "string"; }
function isLegacyLogEntry(entry: unknown): entry is LegacyLogEntry { if (!entry || typeof entry !== "object") return false; const c = entry as Partial<LegacyLogEntry>; return typeof c.id === "string" && typeof c.createdAt === "string" && typeof c.message === "string" && typeof c.category === "string"; }
