import type { ActorLabel, LogBookEntry, PrototypeState, Todo } from "@/types/hotel-operations";
export const PROTOTYPE_STORAGE_KEY_V1 = "hotel-ops-web:prototype:v1";
export const PROTOTYPE_STORAGE_KEY_V2 = "hotel-ops-web:prototype:v2";
export const PROTOTYPE_STORAGE_KEY = "hotel-ops-web:prototype:v3";
type LegacyTodo = Omit<Todo, "updatedAt" | "updatedBy" | "deletedAt" | "deletedBy" | "completedAt" | "completedBy" | "status"> & { status?: string; completedAt?: string | null; completedBy?: string | null; updatedAt?: string; updatedBy?: string | null; deletedAt?: string | null; deletedBy?: string | null };
type LegacyState = { version: 1 | 2 | 3; todos: LegacyTodo[]; logEntries: LogBookEntry[] };
export const SEEDED_PROTOTYPE_STATE: PrototypeState = { version: 3, todos: [
 { id: "seed-todo-204", roomNumber: 204, type: "HOUSEKEEPING_REQUEST", details: "Towel Set", quantity: 2, note: "Guest requested delivery to the room.", status: "OPEN", createdAt: "2026-08-05T10:24:00.000Z", updatedAt: "2026-08-05T10:24:00.000Z", updatedBy: "Front Desk", completedAt: null, completedBy: null, deletedAt: null, deletedBy: null },
 { id: "seed-todo-317", roomNumber: 317, type: "MAINTENANCE_ISSUE", details: "Slow-Draining Sink", quantity: null, note: "Reported during room turnover.", status: "OPEN", createdAt: "2026-08-05T09:48:00.000Z", updatedAt: "2026-08-05T09:48:00.000Z", updatedBy: "Front Desk", completedAt: null, completedBy: null, deletedAt: null, deletedBy: null },
 { id: "seed-todo-508", roomNumber: 508, type: "HOUSEKEEPING_REQUEST", details: "Missing Robe", quantity: 1, note: "Flagged for Housekeeping supervisor review.", status: "OPEN", createdAt: "2026-08-05T07:40:00.000Z", updatedAt: "2026-08-05T07:40:00.000Z", updatedBy: "Front Desk", completedAt: null, completedBy: null, deletedAt: null, deletedBy: null },
 { id: "seed-todo-112-completed", roomNumber: 112, type: "HOUSEKEEPING_REQUEST", details: "Extra Pillows", quantity: 2, note: null, status: "COMPLETED", createdAt: "2026-08-04T17:20:00.000Z", updatedAt: "2026-08-04T17:42:00.000Z", updatedBy: "Housekeeping Supervisor", completedAt: "2026-08-04T17:42:00.000Z", completedBy: "Housekeeping Supervisor", deletedAt: null, deletedBy: null }], logEntries: [
 { id: "seed-log-204", createdAt: "2026-08-05T10:24:00.000Z", roomNumber: 204, message: "Two towel sets requested for Room 204.", category: "Housekeeping", todoId: "seed-todo-204" },
 { id: "seed-log-317", createdAt: "2026-08-05T09:48:00.000Z", roomNumber: 317, message: "Maintenance issue reported for Room 317: Slow-Draining Sink.", category: "Maintenance", todoId: "seed-todo-317" },
 { id: "seed-log-operations-1", createdAt: "2026-08-05T08:15:00.000Z", roomNumber: null, message: "Night audit completed with no escalations.", category: "Operations", todoId: null },
 { id: "seed-log-508", createdAt: "2026-08-05T07:40:00.000Z", roomNumber: 508, message: "One missing robe requested for Room 508.", category: "Housekeeping", todoId: "seed-todo-508" },
 { id: "seed-log-112-completed", createdAt: "2026-08-04T17:42:00.000Z", roomNumber: 112, message: "Housekeeping request completed for Room 112: Extra Pillows.", category: "Housekeeping", todoId: "seed-todo-112-completed" }] };
export function loadPrototypeState(): PrototypeState { if (typeof window === "undefined") return SEEDED_PROTOTYPE_STATE; const v3 = readStoredValue(PROTOTYPE_STORAGE_KEY); if (isLegacyState(v3) && v3.version === 3) return migrateState(v3); const v2 = readStoredValue(PROTOTYPE_STORAGE_KEY_V2); if (isLegacyState(v2) && v2.version === 2) return saveAndReturn(migrateState(v2)); const v1 = readStoredValue(PROTOTYPE_STORAGE_KEY_V1); if (isLegacyState(v1) && v1.version === 1) return saveAndReturn(migrateState(v1)); return SEEDED_PROTOTYPE_STATE; }
export function savePrototypeState(state: PrototypeState) { if (typeof window === "undefined") return; window.localStorage.setItem(PROTOTYPE_STORAGE_KEY, JSON.stringify(state)); }
function saveAndReturn(state: PrototypeState) { savePrototypeState(state); return state; }
function readStoredValue(key: string) { try { const storedValue = window.localStorage.getItem(key); return storedValue ? (JSON.parse(storedValue) as unknown) : null; } catch { return null; } }
function migrateState(state: LegacyState): PrototypeState { return { version: 3, todos: state.todos.filter(isLegacyTodo).map((todo) => ({ id: todo.id, roomNumber: todo.roomNumber, type: todo.type, details: todo.details, quantity: todo.type === "HOUSEKEEPING_REQUEST" ? todo.quantity ?? 1 : null, note: todo.note ?? null, status: todo.status === "COMPLETED" ? "COMPLETED" : todo.status === "DELETED" ? "DELETED" : "OPEN", createdAt: todo.createdAt, updatedAt: todo.updatedAt ?? todo.completedAt ?? todo.createdAt, updatedBy: normalizeActor(todo.updatedBy ?? todo.completedBy), completedAt: todo.completedAt ?? null, completedBy: normalizeActor(todo.completedBy), deletedAt: todo.deletedAt ?? null, deletedBy: normalizeActor(todo.deletedBy) })), logEntries: state.logEntries.filter(isLogEntry) }; }
function isLegacyState(value: unknown): value is LegacyState { if (!value || typeof value !== "object") return false; const c = value as Partial<LegacyState>; return (c.version === 1 || c.version === 2 || c.version === 3) && Array.isArray(c.todos) && Array.isArray(c.logEntries); }
function isLegacyTodo(todo: unknown): todo is LegacyTodo { if (!todo || typeof todo !== "object") return false; const candidate = todo as Partial<LegacyTodo>; return typeof candidate.id === "string" && typeof candidate.roomNumber === "number" && (candidate.type === "HOUSEKEEPING_REQUEST" || candidate.type === "MAINTENANCE_ISSUE") && typeof candidate.details === "string" && typeof candidate.createdAt === "string"; }
function isLogEntry(entry: unknown): entry is LogBookEntry { if (!entry || typeof entry !== "object") return false; const candidate = entry as Partial<LogBookEntry>; return typeof candidate.id === "string" && typeof candidate.createdAt === "string" && typeof candidate.message === "string" && typeof candidate.category === "string"; }
function normalizeActor(actor: string | null | undefined): ActorLabel | null { return actor === "Front Desk" || actor === "Housekeeping Supervisor" || actor === "Maintenance Manager" ? actor : null; }
