import { buildRooms } from "@/lib/rooms";
import { getReceivingShift,isValidLocalDate,SHIFT_HANDOFF_CATEGORIES } from "@/lib/shift-handoff";
import type { ShiftHandoffState } from "@/types/shift-handoff";
export const SHIFT_HANDOFF_STORAGE_KEY="hotel-ops-web:shift-handoffs:v1";
export const EMPTY_SHIFT_HANDOFF_STATE:ShiftHandoffState={version:1,handoffs:[]};
const shifts=["AM","PM","NIGHT"], priorities=["NORMAL","URGENT"], rooms=new Set(buildRooms().map(x=>x.number));
const iso=(x:unknown)=>typeof x==="string"&&x.trim()===x&&!Number.isNaN(Date.parse(x));
const nullableTrimmed=(x:unknown)=>x===null||(typeof x==="string"&&x.trim()===x&&Boolean(x));
export function parseShiftHandoffState(raw:string|null):ShiftHandoffState|null{if(!raw)return null;try{const parsed:unknown=JSON.parse(raw);if(!parsed||typeof parsed!=="object")return null;const state=parsed as Record<string,unknown>;if(state.version!==1||!Array.isArray(state.handoffs))return null;const keys=new Set<string>();for(const value of state.handoffs){if(!value||typeof value!=="object")return null;const h=value as Record<string,unknown>;if(typeof h.id!=="string"||typeof h.localDate!=="string"||!isValidLocalDate(h.localDate)||!shifts.includes(h.fromShift as string)||typeof h.toLocalDate!=="string"||!isValidLocalDate(h.toLocalDate)||!shifts.includes(h.toShift as string)||!Array.isArray(h.items)||typeof h.nothingToReport!=="boolean"||!nullableTrimmed(h.generalNotes)||!nullableTrimmed(h.submittedBy)||!nullableTrimmed(h.acknowledgedBy)||!nullableTrimmed(h.acknowledgementNote)||!(h.submittedAt===null||iso(h.submittedAt))||!(h.acknowledgedAt===null||iso(h.acknowledgedAt))||!iso(h.createdAt)||!iso(h.updatedAt))return null;const mapping=getReceivingShift(h.localDate,h.fromShift as "AM"|"PM"|"NIGHT");if(mapping.toLocalDate!==h.toLocalDate||mapping.toShift!==h.toShift)return null;const key=`${h.localDate}:${h.fromShift}`;if(keys.has(key))return null;keys.add(key);for(const value2 of h.items){if(!value2||typeof value2!=="object")return null;const i=value2 as Record<string,unknown>;if(typeof i.id!=="string"||!SHIFT_HANDOFF_CATEGORIES.includes(i.category as never)||!priorities.includes(i.priority as string)||typeof i.title!=="string"||!i.title||i.title.trim()!==i.title||typeof i.details!=="string"||!i.details||i.details.trim()!==i.details||!(i.roomNumber===null||(Number.isInteger(i.roomNumber)&&rooms.has(i.roomNumber as number)))||typeof i.requiresFollowUp!=="boolean"||!iso(i.createdAt)||!iso(i.updatedAt))return null;}const submitted=Boolean(h.submittedAt),submittedBy=Boolean(h.submittedBy),ack=Boolean(h.acknowledgedAt),ackBy=Boolean(h.acknowledgedBy);if(submitted!==submittedBy||ack!==ackBy||ack&&(!submitted||!submittedBy)||(!submitted&&(h.acknowledgedBy!==null||h.acknowledgementNote!==null))||submitted&&!(h.items.length||(h.nothingToReport===true))||h.nothingToReport&&h.items.length)return null;}return parsed as ShiftHandoffState}catch{return null}}
export function loadShiftHandoffState(){if(typeof window==="undefined")return EMPTY_SHIFT_HANDOFF_STATE;return parseShiftHandoffState(localStorage.getItem(SHIFT_HANDOFF_STORAGE_KEY))??EMPTY_SHIFT_HANDOFF_STATE}
export function saveShiftHandoffState(state:ShiftHandoffState){if(typeof window!=="undefined")localStorage.setItem(SHIFT_HANDOFF_STORAGE_KEY,JSON.stringify(state))}
