import type { FrontDeskShift } from "@/types/front-desk-checklist";
import type { ShiftHandoff,ShiftHandoffItem,ShiftHandoffItemInput,ShiftHandoffState,ShiftHandoffStatus } from "@/types/shift-handoff";
export const SHIFT_HANDOFF_CATEGORIES=["GUEST_ISSUE","ROOM_STATUS","VIP_OR_SPECIAL_REQUEST","BILLING_OR_COMPENSATION","HOUSEKEEPING_OR_MAINTENANCE","TIME_SENSITIVE_REQUEST","SECURITY_OR_INCIDENT","MANAGER_FOLLOW_UP","GENERAL"] as const;
export const CATEGORY_LABELS:Record<(typeof SHIFT_HANDOFF_CATEGORIES)[number],string>={GUEST_ISSUE:"Guest Issue",ROOM_STATUS:"Room Status",VIP_OR_SPECIAL_REQUEST:"VIP / Special Request",BILLING_OR_COMPENSATION:"Billing / Compensation",HOUSEKEEPING_OR_MAINTENANCE:"Housekeeping / Maintenance",TIME_SENSITIVE_REQUEST:"Time-sensitive Request",SECURITY_OR_INCIDENT:"Security / Incident",MANAGER_FOLLOW_UP:"Manager Follow-up",GENERAL:"General"};
export function formatLocalDate(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
export function shiftLocalDate(value:string,days:number){const [y,m,d]=value.split("-").map(Number);const date=new Date(y,m-1,d,12);date.setDate(date.getDate()+days);return formatLocalDate(date)}
export function isValidLocalDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const [y,m,d]=value.split("-").map(Number);const date=new Date(y,m-1,d,12);return date.getFullYear()===y&&date.getMonth()===m-1&&date.getDate()===d}
export function getReceivingShift(localDate:string,fromShift:FrontDeskShift){return fromShift==="AM"?{toLocalDate:localDate,toShift:"PM" as const}:fromShift==="PM"?{toLocalDate:localDate,toShift:"NIGHT" as const}:{toLocalDate:shiftLocalDate(localDate,1),toShift:"AM" as const}}
export function getIncomingHandoffSource(localDate:string,shift:FrontDeskShift){return shift==="AM"?{localDate:shiftLocalDate(localDate,-1),fromShift:"NIGHT" as const}:shift==="PM"?{localDate,fromShift:"AM" as const}:{localDate,fromShift:"PM" as const}}
export function getShiftHandoff(state:ShiftHandoffState,date:string,shift:FrontDeskShift){return state.handoffs.find(x=>x.localDate===date&&x.fromShift===shift)??null}
export function getShiftHandoffStatus(handoff:ShiftHandoff|null):ShiftHandoffStatus{return !handoff?"NOT_STARTED":handoff.acknowledgedAt?"ACKNOWLEDGED":handoff.submittedAt?"SUBMITTED":"DRAFT"}
export function getDailyShiftHandoffStatuses(state:ShiftHandoffState,date:string){return Object.fromEntries((["AM","PM","NIGHT"] as FrontDeskShift[]).map(s=>[s,getShiftHandoffStatus(getShiftHandoff(state,date,s))])) as Record<FrontDeskShift,ShiftHandoffStatus>}
export function getDailyShiftHandoffSummary(state:ShiftHandoffState,date:string){const result={NOT_STARTED:0,DRAFT:0,SUBMITTED:0,ACKNOWLEDGED:0};Object.values(getDailyShiftHandoffStatuses(state,date)).forEach(x=>result[x]++);return result}
export function getHandoffItemCounts(handoff:ShiftHandoff|null){const items=handoff?.items??[];return{total:items.length,urgent:items.filter(x=>x.priority==="URGENT").length,normal:items.filter(x=>x.priority==="NORMAL").length}}
export function sortShiftHandoffItems(items:ShiftHandoffItem[]){return [...items].sort((a,b)=>(a.priority==="URGENT"?0:1)-(b.priority==="URGENT"?0:1)||a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))}
export function getHandoffHistory(state:ShiftHandoffState){const rank={NIGHT:0,PM:1,AM:2};return [...state.handoffs].sort((a,b)=>b.localDate.localeCompare(a.localDate)||rank[a.fromShift]-rank[b.fromShift]||a.id.localeCompare(b.id))}
export function getSubmittedAwaitingAcknowledgement(state:ShiftHandoffState){return getHandoffHistory(state).filter(x=>getShiftHandoffStatus(x)==="SUBMITTED")}
export function filterShiftHandoffs(items:ShiftHandoff[],filters:{date?:string;shift?:FrontDeskShift|"";status?:ShiftHandoffStatus|"";text?:string}){const q=filters.text?.trim().toLowerCase();return items.filter(x=>(!filters.date||x.localDate.includes(filters.date))&&(!filters.shift||x.fromShift===filters.shift)&&(!filters.status||getShiftHandoffStatus(x)===filters.status)&&(!q||[x.submittedBy,x.acknowledgedBy,x.generalNotes,x.acknowledgementNote,...x.items.flatMap(i=>[i.title,i.details,i.roomNumber?.toString()])].some(v=>v?.toLowerCase().includes(q))))}
function id(){return globalThis.crypto?.randomUUID?.()??`handoff-${Date.now()}-${fallback++}`}let fallback=0;
function blank(date:string,shift:FrontDeskShift,now:string):ShiftHandoff{const to=getReceivingShift(date,shift);return{id:id(),localDate:date,fromShift:shift,...to,items:[],generalNotes:null,nothingToReport:false,submittedBy:null,submittedAt:null,acknowledgedBy:null,acknowledgedAt:null,acknowledgementNote:null,createdAt:now,updatedAt:now}}
function update(state:ShiftHandoffState,date:string,shift:FrontDeskShift,fn:(x:ShiftHandoff)=>ShiftHandoff,create=true){const existing=getShiftHandoff(state,date,shift);if(!existing&&!create)return null;const next=fn(existing??blank(date,shift,new Date().toISOString()));return{version:1 as const,handoffs:existing?state.handoffs.map(x=>x.id===existing.id?next:x):[...state.handoffs,next]}}
function validItem(input:ShiftHandoffItemInput,rooms:number[]){return SHIFT_HANDOFF_CATEGORIES.includes(input.category)&&(["NORMAL","URGENT"] as string[]).includes(input.priority)&&Boolean(input.title.trim()&&input.details.trim())&&(input.roomNumber===null||rooms.includes(input.roomNumber))&&typeof input.requiresFollowUp==="boolean"}
export function addHandoffItem(state:ShiftHandoffState,date:string,shift:FrontDeskShift,input:ShiftHandoffItemInput,rooms:number[],now=new Date().toISOString()){if(!validItem(input,rooms)||getShiftHandoff(state,date,shift)?.submittedAt)return null;return update(state,date,shift,x=>({...x,nothingToReport:false,items:[...x.items,{...input,title:input.title.trim(),details:input.details.trim(),id:id(),createdAt:now,updatedAt:now}],updatedAt:now}))}
export function updateHandoffItem(state:ShiftHandoffState,date:string,shift:FrontDeskShift,itemId:string,input:ShiftHandoffItemInput,rooms:number[],now=new Date().toISOString()){if(!validItem(input,rooms))return null;const h=getShiftHandoff(state,date,shift);if(!h||h.submittedAt||!h.items.some(i=>i.id===itemId))return null;return update(state,date,shift,x=>({...x,items:x.items.map(i=>i.id===itemId?{...i,...input,title:input.title.trim(),details:input.details.trim(),updatedAt:now}:i),updatedAt:now}),false)}
export function deleteHandoffItem(state:ShiftHandoffState,date:string,shift:FrontDeskShift,itemId:string,now=new Date().toISOString()){const h=getShiftHandoff(state,date,shift);if(!h||h.submittedAt||!h.items.some(i=>i.id===itemId))return null;return update(state,date,shift,x=>({...x,items:x.items.filter(i=>i.id!==itemId),updatedAt:now}),false)}
export function updateHandoffGeneralNotes(state:ShiftHandoffState,date:string,shift:FrontDeskShift,notes:string,now=new Date().toISOString()){const h=getShiftHandoff(state,date,shift);if(h?.submittedAt||(!h&&!notes.trim()))return null;return update(state,date,shift,x=>({...x,generalNotes:notes.trim()||null,updatedAt:now}))}
export function setNothingToReport(state:ShiftHandoffState,date:string,shift:FrontDeskShift,value:boolean,now=new Date().toISOString()){const h=getShiftHandoff(state,date,shift);if(h?.submittedAt||(value&&h?.items.length))return null;return update(state,date,shift,x=>({...x,nothingToReport:value,updatedAt:now}))}
export function submitHandoff(state:ShiftHandoffState,date:string,shift:FrontDeskShift,name:string,today=formatLocalDate(),now=new Date().toISOString()){const h=getShiftHandoff(state,date,shift);if(!h||h.submittedAt||date>today||(!h.items.length&&!h.nothingToReport)||!name.trim())return null;return update(state,date,shift,x=>({...x,submittedBy:name.trim(),submittedAt:now,updatedAt:now}),false)}
export function acknowledgeHandoff(state:ShiftHandoffState,date:string,shift:FrontDeskShift,name:string,note:string,now=new Date().toISOString()){const h=getShiftHandoff(state,date,shift);if(!h?.submittedAt||h.acknowledgedAt||!name.trim())return null;return update(state,date,shift,x=>({...x,acknowledgedBy:name.trim(),acknowledgedAt:now,acknowledgementNote:note.trim()||null,updatedAt:now}),false)}
export function discardHandoffDraft(state:ShiftHandoffState,date:string,shift:FrontDeskShift){const h=getShiftHandoff(state,date,shift);if(!h||h.submittedAt)return null;return{version:1 as const,handoffs:state.handoffs.filter(x=>x.id!==h.id)}}
