import type { ActorLabel, DemoRole, LogBookEntry, Todo, TodoType } from "@/types/hotel-operations";
export const HOUSEKEEPING_OPTIONS = ["Towel Set", "Extra Towels", "Extra Pillows", "Toiletries", "Linen Replacement", "Missing Room Item", "Missing Robe", "Other"] as const;
export const MAINTENANCE_OPTIONS = ["Air Conditioner Not Cooling", "Television Not Working", "Sink Leaking", "Slow-Draining Sink", "Toilet Issue", "Door Lock Issue", "Lighting Issue", "Other"] as const;
export const ROLE_LABELS: Record<DemoRole, ActorLabel> = { FRONT_DESK: "Front Desk", HOUSEKEEPING_SUPERVISOR: "Housekeeping Supervisor", MAINTENANCE_MANAGER: "Maintenance Manager" };
export type TodoDraft = { roomNumber: number; type: TodoType; details: string; quantity: number | null; note: string | null };
export type TodoUpdate = TodoDraft;
export function getTodoTypeLabel(type: TodoType) { return type === "HOUSEKEEPING_REQUEST" ? "Housekeeping Request" : "Maintenance Issue"; }
export function getTodoTypeShortLabel(type: TodoType) { return type === "HOUSEKEEPING_REQUEST" ? "Housekeeping request" : "Maintenance issue"; }
export function createStableId(prefix: string) { if (typeof crypto !== "undefined" && "randomUUID" in crypto) return `${prefix}-${crypto.randomUUID()}`; return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`; }
export function createTodo(draft: TodoDraft, createdAt = new Date().toISOString()): Todo { return { id: createStableId("todo"), ...draft, status: "OPEN", createdAt, updatedAt: createdAt, updatedBy: "Front Desk", completedAt: null, completedBy: null, deletedAt: null, deletedBy: null }; }
export function updateTodoRecord(todo: Todo, draft: TodoUpdate, actor: ActorLabel, updatedAt = new Date().toISOString()): Todo | null { if (todo.status === "DELETED") return null; const next = { ...todo, ...draft, quantity: draft.type === "HOUSEKEEPING_REQUEST" ? draft.quantity : null }; const changed = next.roomNumber !== todo.roomNumber || next.type !== todo.type || next.details !== todo.details || next.quantity !== todo.quantity || next.note !== todo.note; return changed ? { ...next, updatedAt, updatedBy: actor } : null; }
export function completeTodo(todo: Todo, actor: ActorLabel, completedAt = new Date().toISOString()): Todo | null { if (todo.status !== "OPEN") return null; return { ...todo, status: "COMPLETED", completedAt, completedBy: actor, updatedAt: completedAt, updatedBy: actor }; }
export function deleteTodo(todo: Todo, actor: ActorLabel, deletedAt = new Date().toISOString()): Todo | null { if (todo.status === "DELETED") return null; return { ...todo, status: "DELETED", deletedAt, deletedBy: actor, updatedAt: deletedAt, updatedBy: actor }; }
export function getVisibleTodos(todos: Todo[]) { return todos.filter((todo) => todo.status !== "DELETED"); }
export function getOpenTodos(todos: Todo[]) { return todos.filter((todo) => todo.status === "OPEN").sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
export function getCompletedTodos(todos: Todo[]) { return todos.filter((todo) => todo.status === "COMPLETED").sort((a, b) => (b.completedAt ?? b.updatedAt).localeCompare(a.completedAt ?? a.updatedAt)); }
export function getAllVisibleTodos(todos: Todo[]) { return getVisibleTodos(todos).sort((a, b) => (b.updatedAt || b.completedAt || b.createdAt).localeCompare(a.updatedAt || a.completedAt || a.createdAt)); }
export function getTodosForRoom(todos: Todo[], roomNumber: number) { return getOpenTodos(todos).filter((todo) => todo.roomNumber === roomNumber); }
export function getCompletedTodosForRoom(todos: Todo[], roomNumber: number) { return getCompletedTodos(todos).filter((todo) => todo.roomNumber === roomNumber); }
export function getOpenTodosForRole(todos: Todo[], role: DemoRole) { const type = getTodoTypeForRole(role); return type ? getOpenTodos(todos).filter((todo) => todo.type === type) : []; }
export function getCompletedTodosForRole(todos: Todo[], role: DemoRole) { const type = getTodoTypeForRole(role); return type ? getCompletedTodos(todos).filter((todo) => todo.type === type) : []; }
export function getRoomOperationalIndicators(todos: Todo[], roomNumber: number) { const roomTodos = getTodosForRoom(todos, roomNumber); return { hasHousekeeping: roomTodos.some((todo) => todo.type === "HOUSEKEEPING_REQUEST"), hasMaintenance: roomTodos.some((todo) => todo.type === "MAINTENANCE_ISSUE") }; }
export function getOpenTodoCounts(todos: Todo[]) { const openTodos = getOpenTodos(todos); return { total: openTodos.length, housekeeping: openTodos.filter((todo) => todo.type === "HOUSEKEEPING_REQUEST").length, maintenance: openTodos.filter((todo) => todo.type === "MAINTENANCE_ISSUE").length }; }
export function createTodoLogEntry(todo: Todo): LogBookEntry { const isHousekeeping = todo.type === "HOUSEKEEPING_REQUEST"; return { id: createStableId("log"), createdAt: todo.createdAt, roomNumber: todo.roomNumber, category: isHousekeeping ? "Housekeeping" : "Maintenance", todoId: todo.id, message: isHousekeeping ? `${formatQuantity(todo.quantity)} ${todo.details.toLowerCase()} requested for Room ${todo.roomNumber}.` : `Maintenance issue reported for Room ${todo.roomNumber}: ${todo.details}.` }; }
export function createUpdateLogEntry(before: Todo, after: Todo): LogBookEntry { return { id: createStableId("log"), createdAt: after.updatedAt, roomNumber: after.roomNumber, category: after.type === "HOUSEKEEPING_REQUEST" ? "Housekeeping" : "Maintenance", todoId: after.id, message: updateMessage(before, after) }; }
export function createCompletionLogEntry(todo: Todo): LogBookEntry { return { id: createStableId("log"), createdAt: todo.completedAt ?? new Date().toISOString(), roomNumber: todo.roomNumber, category: todo.type === "HOUSEKEEPING_REQUEST" ? "Housekeeping" : "Maintenance", todoId: todo.id, message: `${getTodoTypeShortLabel(todo.type)} completed for Room ${todo.roomNumber}: ${todo.details}.` }; }
export function createDeletionLogEntry(todo: Todo): LogBookEntry { return { id: createStableId("log"), createdAt: todo.deletedAt ?? new Date().toISOString(), roomNumber: todo.roomNumber, category: todo.type === "HOUSEKEEPING_REQUEST" ? "Housekeeping" : "Maintenance", todoId: todo.id, message: `${getTodoTypeShortLabel(todo.type)} deleted for Room ${todo.roomNumber}: ${todo.details}.` }; }
function updateMessage(before: Todo, after: Todo) { if (before.type !== after.type) return `${getTodoTypeLabel(before.type)} changed to ${getTodoTypeLabel(after.type)} for Room ${after.roomNumber}.`; if (before.roomNumber !== after.roomNumber) return `Request moved from Room ${before.roomNumber} to Room ${after.roomNumber}.`; return `Request updated for Room ${after.roomNumber}: ${after.details}.`; }
function getTodoTypeForRole(role: DemoRole): TodoType | null { if (role === "HOUSEKEEPING_SUPERVISOR") return "HOUSEKEEPING_REQUEST"; if (role === "MAINTENANCE_MANAGER") return "MAINTENANCE_ISSUE"; return null; }
function formatQuantity(quantity: number | null) { if (quantity === 1) return "One"; if (quantity === 2) return "Two"; return `${quantity ?? 1}`; }
