import type { D1Database } from "./cloudflare";
import type { AuthUser } from "./auth";
import { AppError } from "./errors";
export interface TaskInput { roomNumber: string | null; kind: "HOUSEKEEPING_REQUEST" | "MAINTENANCE_ISSUE"; priority: "NORMAL" | "URGENT"; title: string; details: string; dueAt: string | null }
export async function listTasks(db:D1Database,user:AuthUser,limit=50,cursor?:string){ const safe=Math.min(Math.max(limit,1),100); const result=await db.prepare(`SELECT id, room_number AS roomNumber, kind, priority, title, details, status, assigned_user_id AS assignedUserId, due_at AS dueAt, version, created_at AS createdAt, updated_at AS updatedAt FROM tasks WHERE property_id=? AND archived_at IS NULL AND (? IS NULL OR created_at < ?) ORDER BY created_at DESC LIMIT ?`).bind(user.propertyId,cursor??null,cursor??null,safe).all(); return result.results; }
export async function createTask(db:D1Database,user:AuthUser,input:TaskInput){ const id=crypto.randomUUID(), now=new Date().toISOString(); const statements=[db.prepare(`INSERT INTO tasks (id,property_id,room_number,kind,priority,title,details,status,due_at,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'OPEN',?,?,?,?,?)`).bind(id,user.propertyId,input.roomNumber,input.kind,input.priority,input.title,input.details,input.dueAt,user.id,user.id,now,now),db.prepare(`INSERT INTO task_activity (id,property_id,task_id,event_type,actor_user_id,message,created_at) VALUES (?,?,?,'CREATED',?,?,?)`).bind(crypto.randomUUID(),user.propertyId,id,user.id,"Task created",now),db.prepare(`INSERT INTO audit_events (id,property_id,actor_user_id,action,entity_type,entity_id,created_at) VALUES (?,?,?,'task.created','task',?,?)`).bind(crypto.randomUUID(),user.propertyId,user.id,id,now)]; await db.batch(statements); return {id,version:1,createdAt:now}; }
export async function addComment(db:D1Database,user:AuthUser,taskId:string,text:string){ const task=await db.prepare(`SELECT id FROM tasks WHERE id=? AND property_id=? AND archived_at IS NULL`).bind(taskId,user.propertyId).first(); if(!task) throw new AppError("NOT_FOUND","Task not found.",404); const id=crypto.randomUUID(),now=new Date().toISOString(); await db.batch([db.prepare(`INSERT INTO task_comments (id,property_id,task_id,author_user_id,body,created_at) VALUES (?,?,?,?,?,?)`).bind(id,user.propertyId,taskId,user.id,text,now),db.prepare(`INSERT INTO audit_events (id,property_id,actor_user_id,action,entity_type,entity_id,created_at) VALUES (?,?,?,'task.comment_added','task',?,?)`).bind(crypto.randomUUID(),user.propertyId,user.id,taskId,now)]); return {id,createdAt:now}; }
export function isOverdue(dueAt:string|null,now=new Date()):boolean{return Boolean(dueAt&&new Date(dueAt).getTime()<now.getTime())}
export function occurrenceKey(templateId:string,scheduledFor:string):string{return `${templateId}:${scheduledFor}`}
