"use client";
import { useState, type FormEvent } from "react";
import { Modal } from "@/components/dashboard/ui/Modal";
import { RoomPmCompletionForm } from "@/components/room-pm/RoomPmCompletionForm";
import { getRoomPmStatus } from "@/lib/room-pm";
import type { CompleteRoomPmInput, RoomPmRecord } from "@/types/room-pm";
import type { DemoRole } from "@/types/hotel-operations";

const labels = { CURRENT: "Current", DUE_SOON: "Due Soon", OVERDUE: "Overdue", NEVER_COMPLETED: "Never Completed" } as const;
function displayDate(value: string | null): string { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "—"; }
function dateInput(value: string | null): string { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 10); }
export function RoomPmDetails({ record, role, onClose, onComplete, onSchedule, announce }: { record: RoomPmRecord; role: DemoRole; onClose: () => void; onComplete: (input: CompleteRoomPmInput) => void; onSchedule: (nextDueAt: string) => void; announce: (message: string) => void }) {
  const [completionOpen, setCompletionOpen] = useState(false); const [scheduleOpen, setScheduleOpen] = useState(false);
  const canManage = role === "MAINTENANCE_MANAGER";
  return <><Modal title={`Room ${record.roomNumber}`} description="Preventive maintenance details" onClose={onClose} footer={canManage ? <div className="flex flex-wrap justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setScheduleOpen(true)}>Edit Schedule</button><button type="button" className="btn-primary" onClick={() => setCompletionOpen(true)}>Complete PM</button></div> : undefined}><div className="space-y-4"><div className="flex"><StatusBadge record={record} /></div><dl className="grid grid-cols-[130px_minmax(0,1fr)] gap-2 rounded-xl border border-slate-200 p-3 text-sm"><dt className="font-semibold text-slate-500">Last completed</dt><dd>{record.lastCompletedAt ? displayDate(record.lastCompletedAt) : "Never"}</dd><dt className="font-semibold text-slate-500">Completed by</dt><dd>{record.lastCompletedBy ?? "—"}</dd><dt className="font-semibold text-slate-500">Next due</dt><dd>{displayDate(record.nextDueAt)}</dd><dt className="font-semibold text-slate-500">Last note</dt><dd className="break-words">{record.lastNote ?? "—"}</dd></dl><section><h3 className="text-sm font-bold text-slate-950">PM history</h3>{record.history.length ? <ol className="mt-2 space-y-2">{[...record.history].reverse().map((entry) => <li key={entry.id} className="rounded-xl border border-slate-200 p-3 text-sm"><p className="font-bold text-slate-900">{displayDate(entry.completedAt)} · {entry.completedBy}</p><p className="mt-1 text-xs text-slate-600">Next due established: {displayDate(entry.nextDueAt)}</p>{entry.note ? <p className="mt-1 break-words text-slate-700">{entry.note}</p> : null}</li>)}</ol> : <p className="mt-2 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">No PM completion history.</p>}</section></div></Modal>{completionOpen ? <RoomPmCompletionForm roomNumber={record.roomNumber} onClose={() => setCompletionOpen(false)} onSubmit={(input) => { onComplete(input); setCompletionOpen(false); announce(`PM completed for Room ${record.roomNumber}.`); }} /> : null}{scheduleOpen ? <ScheduleForm record={record} onClose={() => setScheduleOpen(false)} onSubmit={(value) => { onSchedule(value); setScheduleOpen(false); announce(`PM schedule updated for Room ${record.roomNumber}.`); }} /> : null}</>;
}
export function StatusBadge({ record }: { record: RoomPmRecord }) { const status = getRoomPmStatus(record); const tone = status === "OVERDUE" ? "bg-red-50 text-red-800 border-red-200" : status === "DUE_SOON" ? "bg-amber-50 text-amber-800 border-amber-200" : status === "CURRENT" ? "bg-emerald-50 text-emerald-800 border-emerald-200" : "bg-slate-100 text-slate-700 border-slate-200"; return <span className={`rounded-full border px-2 py-1 text-xs font-bold ${tone}`}>{labels[status]}</span>; }
function ScheduleForm({ record, onClose, onSubmit }: { record: RoomPmRecord; onClose: () => void; onSubmit: (value: string) => void }) { const [value, setValue] = useState(() => dateInput(record.nextDueAt)); const [error, setError] = useState(""); function submit(event: FormEvent) { event.preventDefault(); try { onSubmit(`${value}T12:00:00`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update schedule."); } } return <Modal title={`Edit Schedule · Room ${record.roomNumber}`} onClose={onClose}><form onSubmit={submit} className="space-y-3"><label className="grid gap-1 text-xs font-semibold text-slate-700">Next due date<input type="date" className="form-input" value={value} onChange={(e) => setValue(e.target.value)} required /></label><p className="text-xs text-slate-500">This changes the schedule only and does not add a completion event.</p>{error ? <p role="alert" className="text-sm font-semibold text-red-700">{error}</p> : null}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button type="submit" className="btn-primary">Save Schedule</button></div></form></Modal>; }
