"use client";
import { useState, type FormEvent } from "react";
import { Modal } from "@/components/dashboard/ui/Modal";
import type { CompleteRoomPmInput } from "@/types/room-pm";

function localDateValue(): string { const now = new Date(); const offset = now.getTimezoneOffset() * 60_000; return new Date(now.getTime() - offset).toISOString().slice(0, 10); }
export function RoomPmCompletionForm({ roomNumber, onClose, onSubmit }: { roomNumber: number; onClose: () => void; onSubmit: (input: CompleteRoomPmInput) => void }) {
  const [completedBy, setCompletedBy] = useState("Maintenance Manager"); const [completedAt, setCompletedAt] = useState(localDateValue); const [nextDueAt, setNextDueAt] = useState(""); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  function submit(event: FormEvent) { event.preventDefault(); if (submitting) return; setSubmitting(true); setError(""); try { onSubmit({ roomNumber, completedBy, completedAt: `${completedAt}T12:00:00`, nextDueAt: `${nextDueAt}T12:00:00`, note }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to complete PM."); setSubmitting(false); } }
  return <Modal title={`Complete PM · Room ${roomNumber}`} onClose={onClose}><form onSubmit={submit} className="space-y-3" noValidate><label className="grid gap-1 text-xs font-semibold text-slate-700">Completed by<input className="form-input" value={completedBy} onChange={(e) => setCompletedBy(e.target.value)} required /></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-semibold text-slate-700">Completion date<input type="date" className="form-input" value={completedAt} onChange={(e) => setCompletedAt(e.target.value)} required /></label><label className="grid gap-1 text-xs font-semibold text-slate-700">Next due date<input type="date" className="form-input" value={nextDueAt} onChange={(e) => setNextDueAt(e.target.value)} required /></label></div><label className="grid gap-1 text-xs font-semibold text-slate-700">Note (optional)<textarea className="form-input" rows={3} value={note} onChange={(e) => setNote(e.target.value)} /></label>{error ? <p role="alert" className="text-sm font-semibold text-red-700">{error}</p> : null}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button type="submit" className="btn-primary" disabled={submitting}>{submitting ? "Saving…" : "Complete PM"}</button></div></form></Modal>;
}
