"use client";
import { useMemo, useState } from "react";
import { RoomPmDetails, StatusBadge } from "@/components/room-pm/RoomPmDetails";
import { useRoomPmState } from "@/hooks/useRoomPmState";
import { filterRoomPmRecords, getRoomPmCounts, getRoomPmRecord, getRoomPmStatus } from "@/lib/room-pm";
import type { RoomPmStatus } from "@/types/room-pm";
import type { DemoRole, Room } from "@/types/hotel-operations";

type Tab = RoomPmStatus | "ALL";
const tabs: { value: Tab; label: string }[] = [{ value: "OVERDUE", label: "Overdue" }, { value: "DUE_SOON", label: "Due Soon" }, { value: "CURRENT", label: "Current" }, { value: "NEVER_COMPLETED", label: "Never Completed" }, { value: "ALL", label: "All" }];
function displayDate(value: string | null): string { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "—"; }
export function RoomPmDashboard({ rooms, role, announce }: { rooms: Room[]; role: DemoRole; announce: (message: string) => void }) {
  const { state, completeRoomPm, updateRoomPmSchedule } = useRoomPmState(); const [tab, setTab] = useState<Tab>("OVERDUE"); const [query, setQuery] = useState(""); const [selectedRoomNumber, setSelectedRoomNumber] = useState<number | null>(null); const counts = getRoomPmCounts(state);
  const records = useMemo(() => filterRoomPmRecords(state.records.filter((record) => tab === "ALL" || getRoomPmStatus(record) === tab), query), [state.records, tab, query]);
  const selected = selectedRoomNumber === null ? null : getRoomPmRecord(state, selectedRoomNumber);
  return <section className="space-y-4"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950">Room PM</h1><p className="mt-1 text-sm text-slate-600">Track preventive maintenance completion and upcoming room due dates.</p></div><dl className="flex flex-wrap gap-2 text-xs font-medium text-slate-700">{tabs.slice(0, 4).map((item) => <div key={item.value} className="flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1.5"><dt>{item.label}</dt><dd className="font-bold">{counts[item.value as RoomPmStatus]}</dd></div>)}</dl><article className="panel"><div className="flex flex-col gap-3"><div className="flex flex-wrap gap-1" role="tablist" aria-label="Room PM status">{tabs.map((item) => <button key={item.value} type="button" role="tab" aria-selected={tab === item.value} onClick={() => setTab(item.value)} className={`min-h-11 rounded-lg px-3 py-2 text-xs font-bold focus:outline-none focus:ring-2 focus:ring-teal-500 sm:min-h-9 ${tab === item.value ? "bg-teal-800 text-white" : "bg-slate-100 text-slate-700 hover:bg-slate-200"}`}>{item.label}{item.value !== "ALL" ? ` (${counts[item.value]})` : ` (${rooms.length})`}</button>)}</div><label className="grid max-w-sm gap-1 text-xs font-semibold text-slate-700">Search<input type="search" className="form-input" placeholder="Room, completed by, or note" value={query} onChange={(e) => setQuery(e.target.value)} /></label></div><p className="mt-3 text-xs font-semibold text-slate-500">Showing {records.length} of {rooms.length} rooms</p>{records.length ? <div className="mt-2 divide-y divide-slate-100">{records.map((record) => { const status = getRoomPmStatus(record); return <article key={record.roomNumber} className="grid gap-2 py-3 text-sm sm:grid-cols-[80px_130px_1fr_1fr_auto] sm:items-center"><p className="font-bold text-slate-950">Room {record.roomNumber}</p><StatusBadge record={record} /><div><p className="text-xs font-semibold text-slate-500">Last completed</p><p>{record.lastCompletedAt ? displayDate(record.lastCompletedAt) : "Never"}{record.lastCompletedBy ? ` · ${record.lastCompletedBy}` : ""}</p></div><div className="min-w-0"><p className="text-xs font-semibold text-slate-500">Next due</p><p className={status === "OVERDUE" || status === "DUE_SOON" ? "font-bold text-slate-900" : ""}>{displayDate(record.nextDueAt)}</p>{record.lastNote ? <p className="truncate text-xs text-slate-500" title={record.lastNote}>{record.lastNote}</p> : null}</div><button type="button" className="btn-secondary" onClick={() => setSelectedRoomNumber(record.roomNumber)}>Details</button></article>; })}</div> : <p className="mt-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">No rooms match this filter.</p>}</article>{selected ? <RoomPmDetails record={selected} role={role} onClose={() => setSelectedRoomNumber(null)} onComplete={completeRoomPm} onSchedule={(nextDueAt) => updateRoomPmSchedule(selected.roomNumber, nextDueAt)} announce={announce} /> : null}</section>;
}
