"use client";
import { useSyncExternalStore } from "react";
import { getAnnouncementDisplayStatus, hasEmployeeReadAnnouncement, normalizeEmployeeName } from "@/lib/announcements";
import { EMPTY_ANNOUNCEMENT_STATE, loadAnnouncementState, saveAnnouncementState } from "@/lib/announcements-storage";
import type { Announcement, AnnouncementDraft, AnnouncementState } from "@/types/announcements";
import type { DemoRole } from "@/types/hotel-operations";
let cache:AnnouncementState|undefined;const listeners=new Set<()=>void>();const stateRef:{current:AnnouncementState}={current:EMPTY_ANNOUNCEMENT_STATE};
const id=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
function snapshot(){if(!cache){cache=loadAnnouncementState();stateRef.current=cache;}return cache;}
function commit(next:AnnouncementState){stateRef.current=next;cache=next;saveAnnouncementState(next);listeners.forEach(f=>f());}
function subscribe(f:()=>void){listeners.add(f);return()=>listeners.delete(f);}
const validDate=(v:string)=>!Number.isNaN(Date.parse(v));
function validDraft(d:AnnouncementDraft){return Boolean(d.title.trim()&&d.message.trim()&&["ALL","FRONT_DESK","HOUSEKEEPING","MAINTENANCE"].includes(d.audience)&&["NORMAL","IMPORTANT","URGENT"].includes(d.priority)&&validDate(d.startsAt)&&(!d.expiresAt||validDate(d.expiresAt)&&Date.parse(d.expiresAt)>Date.parse(d.startsAt)));}
export function useAnnouncementsState(){const state=useSyncExternalStore(subscribe,snapshot,()=>EMPTY_ANNOUNCEMENT_STATE);return {state,setAnnouncementReaderProfile(role:DemoRole,name:string){const clean=name.trim();if(!clean||stateRef.current.readerProfiles[role]===clean)return null;const next={...stateRef.current,readerProfiles:{...stateRef.current.readerProfiles,[role]:clean}};commit(next);return clean;},createAnnouncement(d:AnnouncementDraft,role:DemoRole,creator:string,at=new Date().toISOString()){const clean=creator.trim();if(!clean||!validDraft(d)||!validDate(at))return null;const a:Announcement={...d,title:d.title.trim(),message:d.message.trim(),id:id(),createdByName:clean,createdByRole:role,createdAt:at,updatedAt:at,archivedAt:null,archivedByName:null,archivedByRole:null,readReceipts:[]};commit({...stateRef.current,announcements:[a,...stateRef.current.announcements]});return a;},updateAnnouncement(announcementId:string,d:AnnouncementDraft,role:DemoRole,name:string,at=new Date().toISOString()){const old=stateRef.current.announcements.find(a=>a.id===announcementId);if(!old||old.archivedAt||old.readReceipts.length||old.createdByRole!==role||normalizeEmployeeName(old.createdByName)!==normalizeEmployeeName(name)||!validDraft(d))return null;const changed={...old,...d,title:d.title.trim(),message:d.message.trim(),updatedAt:at};if(JSON.stringify({...old,updatedAt:at})===JSON.stringify(changed))return null;commit({...stateRef.current,announcements:stateRef.current.announcements.map(a=>a.id===old.id?changed:a)});return changed;},markAnnouncementRead(announcementId:string,role:DemoRole,name:string,at=new Date().toISOString()){const clean=name.trim(),old=stateRef.current.announcements.find(a=>a.id===announcementId);if(!old||!clean||!validDate(at)||getAnnouncementDisplayStatus(old,at)!=="ACTIVE"||hasEmployeeReadAnnouncement(old,role,clean))return null;const receipt={id:id(),employeeName:clean,role,readAt:at};const changed={...old,updatedAt:at,readReceipts:[...old.readReceipts,receipt]};commit({...stateRef.current,announcements:stateRef.current.announcements.map(a=>a.id===old.id?changed:a)});return receipt;},archiveAnnouncement(announcementId:string,role:DemoRole,name:string,at=new Date().toISOString()){const clean=name.trim(),old=stateRef.current.announcements.find(a=>a.id===announcementId);if(!old||old.archivedAt||!clean||!validDate(at)||old.createdByRole!==role||normalizeEmployeeName(old.createdByName)!==normalizeEmployeeName(clean))return null;const changed={...old,archivedAt:at,archivedByName:clean,archivedByRole:role,updatedAt:at};commit({...stateRef.current,announcements:stateRef.current.announcements.map(a=>a.id===old.id?changed:a)});return changed;}};}
export function resetAnnouncementsStoreForTests(){cache=undefined;stateRef.current=EMPTY_ANNOUNCEMENT_STATE;listeners.forEach(f=>f());}
