import { useCallback, useRef, useSyncExternalStore } from "react";
import { createLostFoundItem, markLostFoundClaimed, markLostFoundDisposed, markLostFoundReturned, reopenLostFoundItem, replaceItem, updateLostFoundItem } from "@/lib/lost-found";
import { loadLostFoundState, saveLostFoundState, SEEDED_LOST_FOUND_STATE } from "@/lib/lost-found-storage";
import type { LostFoundDraft, LostFoundItem, LostFoundState } from "@/types/lost-found";
let snapshot: LostFoundState | null = null; const listeners = new Set<() => void>();
const subscribe = (listener: () => void) => { listeners.add(listener); return () => listeners.delete(listener); };
const clientSnapshot = () => snapshot ??= loadLostFoundState(); const serverSnapshot = () => SEEDED_LOST_FOUND_STATE;
function publish(state: LostFoundState) { snapshot = state; saveLostFoundState(state); listeners.forEach((listener) => listener()); }
export function useLostFoundState() { const state = useSyncExternalStore(subscribe, clientSnapshot, serverSnapshot); const stateRef = useRef(state); stateRef.current = state; const commit = useCallback((next: LostFoundState | null) => { if (!next) return null; stateRef.current = next; publish(next); return next; }, []); const add = useCallback((draft: LostFoundDraft) => { const item = createLostFoundItem(draft); commit({ version: 1, items: [item, ...stateRef.current.items] }); return item; }, [commit]); const mutate = useCallback((itemId: string, fn: (item: LostFoundItem) => LostFoundItem | null) => commit(replaceItem(stateRef.current, itemId, fn))?.items.find((i) => i.id === itemId) ?? null, [commit]); return { state, createLostFoundItem: add, updateLostFoundItem: (id: string, draft: LostFoundDraft) => mutate(id, (i) => updateLostFoundItem(i, draft)), markLostFoundClaimed: (id: string) => mutate(id, markLostFoundClaimed), markLostFoundReturned: (id: string) => mutate(id, markLostFoundReturned), markLostFoundDisposed: (id: string) => mutate(id, markLostFoundDisposed), reopenLostFoundItem: (id: string) => mutate(id, reopenLostFoundItem) }; }
