"use client";
import {useCallback,useRef,useSyncExternalStore} from "react";
import * as domain from "@/lib/shift-handoff";
import {EMPTY_SHIFT_HANDOFF_STATE,loadShiftHandoffState,saveShiftHandoffState} from "@/lib/shift-handoff-storage";
import type {FrontDeskShift} from "@/types/front-desk-checklist";
import type {ShiftHandoffItemInput,ShiftHandoffState} from "@/types/shift-handoff";
let snapshot:ShiftHandoffState|null=null;const subscribers=new Set<()=>void>();const subscribe=(f:()=>void)=>{subscribers.add(f);return()=>subscribers.delete(f)};const client=()=>snapshot??=loadShiftHandoffState();const server=()=>EMPTY_SHIFT_HANDOFF_STATE;
function publish(state:ShiftHandoffState){snapshot=state;saveShiftHandoffState(state);subscribers.forEach(f=>f())}
export function useShiftHandoffState(){const state=useSyncExternalStore(subscribe,client,server);const stateRef=useRef(state);stateRef.current=state;const commit=useCallback((next:ShiftHandoffState|null)=>{if(!next)return null;stateRef.current=next;publish(next);return next},[]);return{state,
addHandoffItem:useCallback((d:string,s:FrontDeskShift,i:ShiftHandoffItemInput,r:number[])=>commit(domain.addHandoffItem(stateRef.current,d,s,i,r)),[commit]),updateHandoffItem:useCallback((d:string,s:FrontDeskShift,id:string,i:ShiftHandoffItemInput,r:number[])=>commit(domain.updateHandoffItem(stateRef.current,d,s,id,i,r)),[commit]),deleteHandoffItem:useCallback((d:string,s:FrontDeskShift,id:string)=>commit(domain.deleteHandoffItem(stateRef.current,d,s,id)),[commit]),updateHandoffGeneralNotes:useCallback((d:string,s:FrontDeskShift,n:string)=>commit(domain.updateHandoffGeneralNotes(stateRef.current,d,s,n)),[commit]),setNothingToReport:useCallback((d:string,s:FrontDeskShift,v:boolean)=>commit(domain.setNothingToReport(stateRef.current,d,s,v)),[commit]),submitHandoff:useCallback((d:string,s:FrontDeskShift,n:string)=>commit(domain.submitHandoff(stateRef.current,d,s,n)),[commit]),acknowledgeHandoff:useCallback((d:string,s:FrontDeskShift,n:string,note:string)=>commit(domain.acknowledgeHandoff(stateRef.current,d,s,n,note)),[commit]),discardHandoffDraft:useCallback((d:string,s:FrontDeskShift)=>commit(domain.discardHandoffDraft(stateRef.current,d,s)),[commit])}}
