export type Room = { number: number; floor: number };
export type TodoType = "HOUSEKEEPING_REQUEST" | "MAINTENANCE_ISSUE";
export type TodoStatus = "OPEN" | "IN_PROGRESS" | "UNABLE_TO_COMPLETE" | "COMPLETED" | "CANCELLED" | "DELETED";
export type TodoPriority = "NORMAL" | "URGENT";
export type DemoRole = "FRONT_DESK" | "HOUSEKEEPING_SUPERVISOR" | "MAINTENANCE_MANAGER";
export type ActorLabel = "Front Desk" | "Housekeeping Supervisor" | "Maintenance Manager";
export type LogBookEventType = "CREATED" | "UPDATED" | "STARTED" | "COMPLETED" | "UNABLE_TO_COMPLETE" | "REOPENED" | "CANCELLED" | "DELETED" | "NOTE";
export type Todo = {
  id: string;
  roomNumber: number;
  type: TodoType;
  priority: TodoPriority;
  details: string;
  quantity: number | null;
  note: string | null;
  status: TodoStatus;
  createdAt: string;
  updatedAt: string;
  updatedBy: ActorLabel | null;
  startedAt: string | null;
  startedBy: ActorLabel | null;
  completedAt: string | null;
  completedBy: ActorLabel | null;
  resolutionNote: string | null;
  unableAt: string | null;
  unableBy: ActorLabel | null;
  unableReason: string | null;
  unableNote: string | null;
  cancelledAt: string | null;
  cancelledBy: ActorLabel | null;
  cancellationReason: string | null;
  deletedAt: string | null;
  deletedBy: ActorLabel | null;
};
export type LogBookEntry = { id: string; createdAt: string; roomNumber: number | null; message: string; category: "Housekeeping" | "Maintenance" | "Operations"; todoId: string | null; eventType: LogBookEventType; actor: ActorLabel | null; reason: string | null; note: string | null };
export type PrototypeState = { version: 4; todos: Todo[]; logEntries: LogBookEntry[] };
